packages:
  - 'packages/**'

# Define a catalog of version ranges.
catalog:
  fflate: ^0.8.2
  native-copyfiles: ^2.0.1
  remove-glob: ^1.2.0
  sass: ^1.97.3
  typescript: ^5.9.3
  vite: ^7.3.1

overrides:
  vite: 8.0.0-beta.8